name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Patch code snippet
        run: |
          find lib/src/main/java -type f | xargs sed -i -e 's/<pre>{@code/{@snippet lang="java" :/'
          find lib/src/main/java -type f | xargs sed -i -e 's/<\/pre>//'
#         BTW, GJF does not support @snippet, see issues/886
      - name: Build (with Check/Test)
        run: gradle build
  java8:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - name: Patch to support Java8
        run: |
          # FIXME: Better Patch
          # Gradle of Github action does not use spotless@6.13.0 when
          # `version = { require = "[6.13.0, 7.0.0[", prefer = "6.13.0" }`.
          # Therefore, we patch `require` in addition to `prefer`
          sed -i -e 's/\[6.13.0, 7.0.0\[/6.13.0/' gradle/libs.versions.toml
          sed -i -e 's/latest.release/6.13.0/' gradle/libs.versions.toml
          sed -i -e 's/JavaLanguageVersion.of(\d{1,2})/JavaLanguageVersion.of(8)/' lib/build.gradle.kts
          cat gradle/libs.versions.toml
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Test
        run: gradle test
